const fs = require('fs');
const T = 'C:/Users/ubaidullah/Desktop/Accounts/src/pages/staff/RegisterPersonPage.tsx';
const p = [];
const a = (s) => p.push(s);
a('// src/pages/staff/RegisterPersonPage.tsx');
a('import { useState, useEffect, useRef } from "react";');
a('import { motion, AnimatePresence } from "framer-motion";');
a('import { useNavigate } from "react-router-dom";');
a('import {');
a('  User, Phone, Shield, ChevronRight, ChevronLeft, Eye, EyeOff,');
a('  Upload, Check, Loader2, AlertCircle, Building2, MapPin,');
a('  ChevronDown, Briefcase, Search, X, CheckCircle2,');
a('} from "lucide-react";');
a('import { locationApi } from "../../api/locationApi";');
a('import { personsApi } from "../../api/personsApi";');
a('import type { RegisterPersonDto, OrgTreeNodeDto } from "../../api/personsApi";');
a('import { staffApi } from "../../api/staffApi";');
a('import { positionApi } from "../../api/positionApi";');
a('import RegistrationSuccessModal from "../../components/staff/RegistrationSuccessModal";');
a('import type { CountryDto, ProvinceDto, VacancyDto } from "../../types";');
a('');
a('// ── Step definitions');
a('const STEPS = [');
a('  { id: 1, label: "Vacancy",       icon: "Briefcase" },');
a('  { id: 2, label: "Personal",      icon: "User"      },');
a('  { id: 3, label: "Contact",       icon: "MapPin"    },');
a('  { id: 4, label: "System Access", icon: "Shield"    },');
a('  { id: 5, label: "Review",        icon: "Check"     },');
a('] as const;');
a('');
a('interface AddressForm {');
a('  addressLine: string;');
a('  country: string;');
a('  province: string;');
a('  city: string;');
a('  district: string;');
a('  postalCode: string;');
a('}');
a('');
a('const emptyAddress = (): AddressForm => ({');
a('  addressLine: "", country: "", province: "", city: "", district: "", postalCode: "",');
a('});');
a('');
