import { appendFileSync } from 'fs';
const TARGET = 'C:/Users/ubaidullah/Desktop/Accounts/src/pages/staff/RegisterPersonPage.tsx';
const L = (s) => appendFileSync(TARGET, s + '\n', 'utf8');

// ── Main component opening + state declarations
L('// ── Main Page');
L('export default function RegisterPersonPage() {');
L('  const navigate = useNavigate();');
L('  const [step, setStep] = useState(1);');
L('  const [submitting, setSubmitting] = useState(false);');
L('  const [apiError, setApiError] = useState<string | null>(null);');
L('');
L('  // Step 1 – Vacancy');
L('  const [vacancies, setVacancies] = useState<VacancyDto[]>([]);');
L('  const [loadingVacancies, setLoadingVacancies] = useState(true);');
L('  const [vacancySearch, setVacancySearch] = useState("");');
L('  const [selectedVacancy, setSelectedVacancy] = useState<VacancyDto | null>(null);');
L('');
L('  // Step 2 – Personal Info');
L('  const [fullName, setFullName] = useState("");');
L('  const [gender, setGender] = useState("");');
L('  const [dateOfBirth, setDateOfBirth] = useState("");');
L('  const [maritalStatus, setMaritalStatus] = useState("");');
L('  const [photoFile, setPhotoFile] = useState<File | null>(null);');
L('  const [photoPreview, setPhotoPreview] = useState<string | null>(null);');
L('  const photoInputRef = useRef<HTMLInputElement>(null);');
L('');
L('  // Step 3 – Contact & Address');
L('  const [phone, setPhone] = useState("");');
L('  const [email, setEmail] = useState("");');
L('  const [currentAddress, setCurrentAddress] = useState<AddressForm>(emptyAddress());');
L('  const [permanentAddress, setPermanentAddress] = useState<AddressForm>(emptyAddress());');
L('  const [sameAsCurrent, setSameAsCurrent] = useState(false);');
L('  const [countries, setCountries] = useState<CountryDto[]>([]);');
L('');
L('  // Step 4 – System Access');
L('  const [orgTree, setOrgTree] = useState<OrgTreeNodeDto[]>([]);');
L('  const [selectedCountryNode, setSelectedCountryNode] = useState<OrgTreeNodeDto | null>(null);');
L('  const [selectedCompanyNode, setSelectedCompanyNode] = useState<OrgTreeNodeDto | null>(null);');
L('  const [selectedBranchNode, setSelectedBranchNode] = useState<OrgTreeNodeDto | null>(null);');
L('  const [previewLoginId, setPreviewLoginId] = useState("");');
L('  const [previewCompanyName, setPreviewCompanyName] = useState("");');
L('  const [loadingPreview, setLoadingPreview] = useState(false);');
L('  const [password, setPassword] = useState("");');
L('  const [confirmPassword, setConfirmPassword] = useState("");');
L('  const [showPassword, setShowPassword] = useState(false);');
L('  const [showConfirm, setShowConfirm] = useState(false);');
L('');
L('  // Step 5 – Success modal');
L('  const [showSuccess, setShowSuccess] = useState(false);');
L('  const [successData, setSuccessData] = useState({ loginId: "", password: "", staffName: "", jobTitle: "", vacancyCode: "", branchName: "" });');
L('');
console.log('Part 5 done');
