/** Swagger v1 path catalog — http://localhost:5099/swagger/v1/swagger.json */

export const API = {
  auth: {
    register: '/api/auth/register',
    login: '/api/auth/login',
    logout: '/api/auth/logout',
    session: '/api/auth/session',
    assignRole: '/api/auth/assign-role',
    users: '/api/auth/users',
  },
  access: {
    features: '/api/access/features',
    featuresByModule: (m: string) => `/api/access/features/module/${encodeURIComponent(m)}`,
    groups: '/api/access/groups',
    group: (id: number) => `/api/access/groups/${id}`,
    groupFeatures: (id: number) => `/api/access/groups/${id}/features`,
    groupSync: (id: number) => `/api/access/groups/${id}/sync`,
    staffGroups: (sid: string) => `/api/access/staff/${encodeURIComponent(sid)}/groups`,
    staffGroup: (sid: string, gid: number) =>
      `/api/access/staff/${encodeURIComponent(sid)}/groups/${gid}`,
    staffPermissions: (sid: string) => `/api/access/staff/${encodeURIComponent(sid)}/permissions`,
    deptPersons: (deptId: string) => `/api/access/department/${encodeURIComponent(deptId)}/persons`,
    deptMatrix: (deptId: string) => `/api/access/department/${encodeURIComponent(deptId)}/matrix`,
    staffFeature: (sid: string, key: string) =>
      `/api/access/staff/${encodeURIComponent(sid)}/feature/${encodeURIComponent(key)}`,
    staffGrantAll: (sid: string) => `/api/access/staff/${encodeURIComponent(sid)}/grant-all`,
    staffRevokeAll: (sid: string) => `/api/access/staff/${encodeURIComponent(sid)}/revoke-all`,
  },
  rbac: {
    sidebar: '/api/rbac/sidebar',
    menuPermissions: '/api/rbac/menu-permissions',
    staffHasAccess: (sid: string, key: string) =>
      `/api/rbac/staff/${encodeURIComponent(sid)}/has-access/${encodeURIComponent(key)}`,
    staffEffectivePermissions: (sid: string) =>
      `/api/rbac/staff/${encodeURIComponent(sid)}/effective-permissions`,
    staffOverrides: (sid: string) => `/api/rbac/staff/${encodeURIComponent(sid)}/overrides`,
    staffOverride: (sid: string, key: string) =>
      `/api/rbac/staff/${encodeURIComponent(sid)}/overrides/${encodeURIComponent(key)}`,
    grantMenu: (sid: string, menuId: number) =>
      `/api/rbac/staff/${encodeURIComponent(sid)}/grant-menu/${menuId}`,
    revokeMenu: (sid: string, menuId: number) =>
      `/api/rbac/staff/${encodeURIComponent(sid)}/revoke-menu/${menuId}`,
    menuFeatureKeys: (menuId: number) => `/api/rbac/menus/${menuId}/feature-keys`,
    matrix: (deptId: string | number) => `/api/rbac/matrix/${deptId}`,
    rolePermissions: (jobTitle: string) =>
      `/api/rbac/roles/${encodeURIComponent(jobTitle)}/permissions`,
    seedFeatures: '/api/rbac/seed-features',
  },
  data: {
    accessible: '/api/data/accessible',
    myPermissions: '/api/data/my-permissions',
    canAccess: (key: string) => `/api/data/can-access/${encodeURIComponent(key)}`,
    departments: '/api/data/departments',
    staff: '/api/data/staff',
    persons: '/api/data/persons',
    orgEmployees: (id: number | string) => `/api/data/org/${id}/employees`,
    orgVacancyPersons: (id: number | string) => `/api/data/org/${id}/vacancy-persons`,
  },
  appNotes: {
    visible: '/api/app-notes/visible',
    loginInstructions: '/api/app-notes/login-instructions',
    adminInstructions: '/api/app-notes/admin/instructions',
    note: (id: number) => `/api/app-notes/${id}`,
    unreadCount: '/api/app-notes/unread-count',
    root: '/api/app-notes',
    markRead: (id: number) => `/api/app-notes/${id}/mark-read`,
    acknowledge: (id: number) => `/api/app-notes/${id}/acknowledge`,
    dismiss: (id: number) => `/api/app-notes/${id}/dismiss`,
  },
  appLookups: {
    all: '/api/app-lookups/all',
    byType: (code: string) => `/api/app-lookups/${encodeURIComponent(code)}`,
  },
  appMenuDefinitions: { active: '/api/app-menu-definitions/active' },
  menus: {
    root: '/api/Menus',
    sidebarTree: '/api/Menus/sidebar-tree',
    withPermissions: '/api/Menus/with-permissions',
    menu: (id: number) => `/api/Menus/${id}`,
    menuPermissions: (id: number) => `/api/Menus/${id}/permissions`,
    bulkPermissions: '/api/Menus/bulk-permissions',
    seed: '/api/Menus/seed',
  },
  organization: {
    countryLookup: '/api/organization/country-lookup',
    countrySearch: '/api/organization/country-search',
    tree: '/api/organization/tree',
    treeFrom: (id: number) => `/api/organization/tree/${id}`,
    flatTree: '/api/organization/flat-tree',
    root: '/api/organization',
    node: (id: number) => `/api/organization/${id}`,
    children: (id: number) => `/api/organization/${id}/children`,
    byLabel: (label: string) => `/api/organization/by-label/${encodeURIComponent(label)}`,
    search: '/api/organization/search',
    vacancyPersons: (orgId: number | string) => `/api/organization/${orgId}/vacancy-persons`,
    employeesByRole: (orgId: number | string) => `/api/organization/${orgId}/employees-by-role`,
  },
  persons: {
    profiles: '/api/Persons/profiles',
    profile: (id: string) => `/api/Persons/${encodeURIComponent(id)}/profile`,
    orgTree: '/api/Persons/org-tree',
    previewLoginId: '/api/Persons/preview-login-id',
    previewEmail: '/api/Persons/preview-email',
    root: '/api/Persons',
    unassigned: '/api/Persons/unassigned',
    person: (id: string) => `/api/Persons/${encodeURIComponent(id)}`,
    registerRaw: '/api/Persons/register-raw',
    register: '/api/Persons/register',
    uploadPhoto: (id: string) => `/api/Persons/${encodeURIComponent(id)}/upload-photo`,
    changePassword: (id: string) => `/api/Persons/${encodeURIComponent(id)}/change-password`,
    resetPassword: (id: string) => `/api/Persons/${encodeURIComponent(id)}/reset-password`,
    resetToDefaultPassword: (id: string) =>
      `/api/Persons/${encodeURIComponent(id)}/reset-to-default-password`,
  },
  employees: {
    root: '/api/employees',
    employee: (id: string) => `/api/employees/${encodeURIComponent(id)}`,
    search: '/api/employees/search',
    hire: (vacancyId: string) => `/api/employees/hire/${encodeURIComponent(vacancyId)}`,
    hirePerson: (vacancyId: string) => `/api/employees/hire-person/${encodeURIComponent(vacancyId)}`,
    uploadPhoto: (id: string) => `/api/employees/${encodeURIComponent(id)}/upload-photo`,
    photo: (id: string) => `/api/employees/${encodeURIComponent(id)}/photo`,
    transfer: (id: string) => `/api/employees/${encodeURIComponent(id)}/transfer`,
  },
  positions: {
    root: '/api/positions',
    position: (id: string) => `/api/positions/${encodeURIComponent(id)}`,
    vacant: '/api/positions/vacant',
    filled: '/api/positions/filled',
    byNode: (orgId: number) => `/api/positions/by-node/${orgId}`,
    report: '/api/positions/report',
    previewCode: '/api/positions/preview-code',
    bulk: '/api/positions/bulk',
  },
  locations: {
    countries: '/api/locations/countries',
    provinces: '/api/locations/provinces',
    cities: '/api/locations/cities',
    full: '/api/locations/full',
    countriesSearch: '/api/locations/countries/search',
  },
} as const;
